scpOutputDir="las@zueub241:/srn/las/www/satellite/DATA/MSG_%(rgb)s-%(area)s_/"
scpID="-i $PYTROLLHOME/scripts/id_rsa_las"
#scpOutputDir="las@lomux240:/www/proj/OTL/WOL/cll/satimages"
#scpID="-i /opt/users/$LOGNAME/monti-pytroll/scripts/id_dsa_las"
#scpOutputDir="las@zueub241:/srn/las/www/satellite/DATA/"
#scpID="-i /opt/users/$LOGNAME/monti-pytroll/scripts/id_rsa_las"
